project_name: --
dataset: --
num_trials: --
num_workers: 8
is_using_wandb: --

model:
  n: --
  prior: --
  pred: --
  stump_init: ones
  samples_prop: 0.5
  max_tree_depth: None
  posterior_std: --
  output: class

training:
  seed: --
  lr: 0.1
  batch_size: 1024
  num_epochs: 100
  risk: --
  distribution: --
  rand_N: --
  compute_disintegration: False
  normalize_data: True
  splits: [0.6, 0.2, 0.2]

bound:
  delta: 0.05
  type: "seeger"
  order: --
  n_grid: --