project_name: "DeterministicPACBayes"
num_trials: 10
num_workers: 8 # for dataloaders
is_using_wandb: False

model:
  M: 10 # number of predictors, if stumps: 2*M per dimension
  prior: 0 # param of the distribution prior
  pred: "stumps-uniform" # stumps-uniform, rf
  stump_init: "rand" # ones, rand
  bootstrap: 0.5 # only for pred = rf
  tree_depth: None # only for pred = rf

training:
  seed: 541944
  lr: 0.1
  batch_size: 1024
  num_epochs: 100
  risk: "Dis_Renyi" # FO, SO, Bin, Dis_Renyi, Dis_KL
  distribution: "gaussian" # "dirichlet", "gaussian", "categorical"
  opt_bound: True # if False, optimize only risk
  rand_n: 0 # only for Bin


dataset: 'SVMGUIDE'

#dataset:
#  distr: moons
#  noise: 0.05
#  N_train: 1000 # number of training points per class
#  N_test: 1000 # number of test points per class

bound:
  delta: 0.05
  type: "seeger"
  order: 1.5
  n_grid: 5